spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/zero_one_task1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always